In [1]:
def f(x):
    y = x**3 - x**2 - x - 1 #input fungsinya
    return(y)
def secant(f,x0,x1,TOL,MAX):
    N=1
    xOld=x0
    xNew=x1
    while N<=MAX:
        N+=1
        x=xNew-(f(xNew)*(xNew-xOld)/(f(xNew)-f(xOld)))
        xOld=xNew
        xNew=x
        if abs(f(x))<TOL:
            print(x)
            break
    else:
        print("Metode Secant Gagal")
    return (x)

MAX=float(input("Masukkan iterasi maksimal : "))
secant(f,1,2,1e-6,MAX)

Masukkan iterasi maksimal : 10
1.8392867552269239

1.8392867552269239

In [9]:
import pandas as pd
import numpy as np
def f(x) :
    return (x**3 - x**2 - x - 1)
    
def secant(x0,x1,error):
    i = 0
    xOld=x0
    xNew=x1
    while True:
            
        x = xNew-(f(xNew)*(xNew-xOld)/(f(xNew)-f(xOld)))
        if i == 0 :
            A=np.array([[xOld, xNew , x,f(xOld),f(xNew),abs(x-xNew), error]])
        else :
            A=np.append(A,[[xOld, xNew , x,f(xOld),f(xNew),abs(x-xNew),error]],axis=0)

        if abs(xNew-xOld)<error:
                return x,A

        xOld=xNew
        xNew=x

        i+=1
            
akar, table = secant(2,1,1e-6)
df = pd.DataFrame(table,columns=['x0', 'x1' , 'x2','f(x0)','f(x1)','|x2-x1|','error'])
df['|x2-x1| < error'] = df['|x2-x1|'] < df['error']
df = df.iloc[:-1]
df

,x0,x1,x2,f(x0),f(x1),|x2-x1|,error,|x2-x1| < error
0,2.000000,1.000000,1.666667,1.000000,-2.000000e+00,6.666667e-01,0.000001,False
1,1.000000,1.666667,2.125000,-2.000000,-8.148148e-01,4.583333e-01,0.000001,False
2,1.666667,2.125000,1.801494,-0.814815,1.955078e+00,3.235062e-01,0.000001,False
3,2.125000,1.801494,1.831563,1.955078,-2.003418e-01,3.006923e-02,0.000001,False
4,1.801494,1.831563,1.839535,-0.200342,-4.198234e-02,7.971590e-03,0.000001,False
5,1.831563,1.839535,1.839285,-0.041982,1.356295e-03,2.494731e-04,0.000001,False
6,1.839535,1.839285,1.839287,0.001356,-8.689073e-06,1.588070e-06,0.000001,False
7,1.839285,1.839287,1.839287,-0.000009,-1.778592e-09,3.251335e-10,0.000001,True

In [10]:
import pandas as pd
import numpy as np
def f(x) :
    return (- 1/2 - np.sin(x) + np.cos(x))
    
def secant(x0,x1,error):
    i = 0
    xOld=x0
    xNew=x1
    while True:
            
        x = xNew-(f(xNew)*(xNew-xOld)/(f(xNew)-f(xOld)))
        if i == 0 :
            A=np.array([[xOld, xNew , x,f(xOld),f(xNew),abs(x-xNew), error]])
        else :
            A=np.append(A,[[xOld, xNew , x,f(xOld),f(xNew),abs(x-xNew),error]],axis=0)

        if abs(xNew-xOld)<error:
                return x,A

        xOld=xNew
        xNew=x

        i+=1
            
akar, table = secant(1,0,1e-6)
df = pd.DataFrame(table,columns=['x0', 'x1' , 'x2','f(x0)','f(x1)','|x2-x1|','error'])
df['|x2-x1| < error'] = df['|x2-x1|'] < df['error']
df = df.iloc[:-1]
df

,x0,x1,x2,f(x0),f(x1),|x2-x1|,error,|x2-x1| < error
0,1.000000,0.000000,0.384270,-0.801169,5.000000e-01,3.842699e-01,0.000001,False
1,0.000000,0.384270,0.429055,0.500000,5.218996e-02,4.478469e-02,0.000001,False
2,0.384270,0.429055,0.423992,0.052190,-6.651850e-03,5.062744e-03,0.000001,False
3,0.429055,0.423992,0.424031,-0.006652,5.181144e-05,3.912907e-05,0.000001,False
4,0.423992,0.424031,0.424031,0.000052,4.892622e-08,3.698502e-08,0.000001,True

In [2]:
import numpy as np

def f(x):
    y = x + np.exp(-x**2) #input fungsinya
    return(y)
def secant(f,x0,x1,TOL,MAX):
    N=1
    xOld=x0
    xNew=x1
    while N<=MAX:
        N+=1
        x=xNew-(f(xNew)*(xNew-xOld)/(f(xNew)-f(xOld)))
        xOld=xNew
        xNew=x
        if abs(f(x))<TOL:
            print(x)
            break
    else:
        print("Metode Secant Gagal")
    return (x)

MAX=float(input("Masukkan iterasi maksimal : "))
secant(f,-1,0,1e-5,MAX)

Masukkan iterasi maksimal : 5
-0.6529186305192649

-0.6529186305192649

In [11]:
import pandas as pd
import numpy as np
def f(x) :
    return (x + np.exp(-x**2))
    
def secant(x0,x1,error):
    i = 0
    xOld=x0
    xNew=x1
    while True:
            
        x = xNew-(f(xNew)*(xNew-xOld)/(f(xNew)-f(xOld)))
        if i == 0 :
            A=np.array([[xOld, xNew , x,f(xOld),f(xNew),abs(x-xNew), error]])
        else :
            A=np.append(A,[[xOld, xNew , x,f(xOld),f(xNew),abs(x-xNew),error]],axis=0)

        if abs(xNew-xOld)<error:
                return x,A

        xOld=xNew
        xNew=x

        i+=1
            
akar, table = secant(-1,0,1e-5)
df = pd.DataFrame(table,columns=['x0', 'x1' , 'x2','f(x0)','f(x1)','|x2-x1|','error'])
df['|x2-x1| < error'] = df['|x2-x1|'] < df['error']
df = df.iloc[:-1]
df

,x0,x1,x2,f(x0),f(x1),|x2-x1|,error,|x2-x1| < error
0,-1.000000,0.000000,-0.612700,-0.632121,1.000000e+00,6.126998e-01,0.00001,False
1,0.000000,-0.612700,-0.661887,1.000000,7.431383e-02,4.918738e-02,0.00001,False
2,-0.612700,-0.661887,-0.652896,0.074314,-1.662253e-02,8.991106e-03,0.00001,False
3,-0.661887,-0.652896,-0.652919,-0.016623,4.174754e-05,2.252463e-05,0.00001,False
4,-0.652896,-0.652919,-0.652919,0.000042,1.834068e-08,9.899951e-09,0.00001,True